const stripe = require('stripe')(process.env.CONNECT_SK);
const ADMIN_ACCOUNT_ID = process.env.ADMIN_ACCOUNT_ID;
const nodemailer = require('nodemailer');

async function muteHandler(handler) {
  let muteHandler = handler;

  return muteHandler;
}

async function createTransfer(intent) {
  let total = intent.amount;

  let fee = Math.round(total * 0.04 + 30);

  let amount = total - fee;

  let transactionSource = intent.charges.data[0].id;

  try {
    const transfer = await stripe.transfers.create({
      amount: amount,
      currency: 'usd',
      destination: ADMIN_ACCOUNT_ID,
      transfer_group: intent.transfer_group,
      source_transaction: transactionSource,
    });

    if (!transfer) {
      console.log('Transfer failed: ', transfer);
    }
    return transfer;
  } catch (err) {
    return;
  }
}

async function newInvoice(data) {
  console.log('Generating email...');
  let transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_PASS,
    },
  });

  await transporter.sendMail({
    from: 'donotreply.leyline.dev',
    to: 'mjbergeron@leyline.dev',
    subject: `New Invoice Created by ${data.account_name}`,
    // text: `A new Invoice has been created by Evidenced Nutrition.\nThis is the new line.`,
    html: `<p><b>New Invoice Generated by ${data.account_name}</b></p><p>Invoice: ${data.id}</p><p>Amount Due: $${(data.amount_due)/100}</p><p>Customer: ${data.customer}</p><p>Description: ${data.description}</p><p>Due Date: ${data.due_data}</p>`,
  });
  console.log('Email sent.');
}

async function invoiceFinalized(data) {
  console.log('Generating email...');
  let transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_PASS,
    },
  });

  await transporter.sendMail({
    from: 'donotreply.leyline.dev',
    to: 'mjbergeron@leyline.dev',
    subject: `Invoice by ${data.account_name} Finalized.`,
    // text: `A new Invoice has been created by Evidenced Nutrition.\nThis is the new line.`,
    html: `<p><b>New Invoice by ${data.account_name} has been finalized.</b></p><p>Invoice: ${data.id}</p><p>Amount Due: $${(data.amount_due)/100}</p><p>Amount Paid: $${(data.amount_paid)/100}</p><p>Amount Remaining: ${data.amount_remaining}</p><p>Charge: ${data.charge}</p><p>Payment Intent: ${data.payment_intent}</p><p>Customer: ${data.customer}</p><p>Description: ${data.description}</p><p>Status: ${data.status}</p><p>Paid At: ${data.status_transitions.paid_at}</p><p>Finalized At: ${data.status_transitions.finalized_at}</p><p>Subscription: ${data.subscription}</p>`,
  });
  console.log('Email sent.');
}

module.exports = {
  createTransfer,
  muteHandler,
  newInvoice,
  invoiceFinalized
};
